web1:
  image: dkdde/forgetit_web
  links:
    - db1
    - alfresco
    - gate
    - influxdb
    - mimir1:mimir
  environment:
    DB_HOST: "db1"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web1"
    FISH_EVALUATION: "dkd"
    START_DELAY: 20
web2:
  image: dkdde/forgetit_web
  links:
    - db2
    - alfresco
    - gate
    - influxdb
    - mimir2:mimir
  environment:
    DB_HOST: "db2"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web2"
    FISH_EVALUATION: "dkd"
    START_DELAY: 40
web3:
  image: dkdde/forgetit_web
  links:
    - db3
    - alfresco
    - gate
    - influxdb
    - mimir3:mimir
  environment:
    DB_HOST: "db3"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web3"
    FISH_EVALUATION: "dkd"
    START_DELAY: 60
web4:
  image: dkdde/forgetit_web
  links:
    - db4
    - alfresco
    - gate
    - influxdb
    - mimir4:mimir
  environment:
    DB_HOST: "db4"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web4"
    FISH_EVALUATION: "dkd"
    START_DELAY: 80
web5:
  image: dkdde/forgetit_web
  links:
    - db5
    - alfresco
    - gate
    - influxdb
    - mimir5:mimir
  environment:
    DB_HOST: "db5"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web5"
    FISH_EVALUATION: "dkd"
    START_DELAY: 100
web6:
  image: dkdde/forgetit_web
  links:
    - db6
    - alfresco
    - gate
    - influxdb
    - mimir6:mimir
  environment:
    DB_HOST: "db6"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web6"
    FISH_EVALUATION: "dkd"
    START_DELAY: 120
nginx:
  image: "dkdde/fish_nginx"
  ports:
    - "80:80"
  volumes:
    - ./passwd:/etc/nginx/passwd
  links:
    - web1
    - web2
    - web3
    - web4
    - web5
    - web6
    - alfresco
    - influxdb
    - chronograph
db1:
  image: tutum/mysql:5.5
  environment:
    MYSQL_USER: "admin"
    MYSQL_PASS: "KtE0uD5dK4rv"
    STARTUP_SQL: "/tmp/mounted/db1.sql"
  volumes:
    - ./database:/tmp/mounted
db2:
  image: tutum/mysql:5.5
  environment:
    MYSQL_USER: "admin"
    MYSQL_PASS: "KtE0uD5dK4rv"
    STARTUP_SQL: "/tmp/mounted/db2.sql"
  volumes:
    - ./database:/tmp/mounted
db3:
  image: tutum/mysql:5.5
  environment:
    MYSQL_USER: "admin"
    MYSQL_PASS: "KtE0uD5dK4rv"
    STARTUP_SQL: "/tmp/mounted/db3.sql"
  volumes:
    - ./database:/tmp/mounted
db4:
  image: tutum/mysql:5.5
  environment:
    MYSQL_USER: "admin"
    MYSQL_PASS: "KtE0uD5dK4rv"
    STARTUP_SQL: "/tmp/mounted/db4.sql"
  volumes:
    - ./database:/tmp/mounted
db5:
  image: tutum/mysql:5.5
  environment:
    MYSQL_USER: "admin"
    MYSQL_PASS: "KtE0uD5dK4rv"
    STARTUP_SQL: "/tmp/mounted/db5.sql"
  volumes:
    - ./database:/tmp/mounted
db6:
  image: tutum/mysql:5.5
  environment:
    MYSQL_USER: "admin"
    MYSQL_PASS: "KtE0uD5dK4rv"
    STARTUP_SQL: "/tmp/mounted/db6.sql"
  volumes:
    - ./database:/tmp/mounted
gate:
  image: dkdde/forgetit_gate
alfresco:
   image: dkdde/forgetit_typo3_alfresco:latest
influxdb:
  image: tutum/influxdb:0.9
  environment:
    PRE_CREATE_DB: "typo3"
mimir1:
  image: dkdde/forgetit_mimir
mimir2:
  image: dkdde/forgetit_mimir
mimir3:
  image: dkdde/forgetit_mimir
mimir4:
  image: dkdde/forgetit_mimir
mimir5:
  image: dkdde/forgetit_mimir
mimir6:
  image: dkdde/forgetit_mimir
chronograph:
  image: lukasmartinelli/chronograf
  environment:
    INFLUXDB_HOST: "influxdb"
  links:
    - influxdb
