web1:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web1"
web2:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web2"
web3:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web3"
web4:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web4"
web5:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web5"
web6:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web6"
web7:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web7"
web8:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web8"
web9:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web9"
web10:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web10"
nginx:
  build: .
#  image: "dkdde/fish_nginx"
  ports:
    - "80:80"
  volumes:
    - passwd:/etc/nginx/passwd
  links:
    - web1
    - web2
    - web3
    - web4
    - web5
    - web6
    - web7
    - web8
    - web9
    - web10
    - db
    - gate
    - alfresco
db:
  image: tutum/mysql:5.5
  environment:
    MYSQL_USER: "admin"
    MYSQL_PASS: "KtE0uD5dK4rv"
    STARTUP_SQL: "/tmp/mounted/initialDatabase.sql"
gate:
  image: dkdde/forgetit_gate
alfresco:
   image: dkdde/forgetit_typo3_alfresco:latest
influxdb:
  image: tutum/influxdb:staging-0.9.0-rc
  environment:
    PRE_CREATE_DB: "typo3"
mimir:
  image: dkdde/forgetit_mimir
