web1:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web1"
    START_DELAY: 20
web2:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web2"
    START_DELAY: 40
web3:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web3"
    START_DELAY: 60
web4:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web4"
    START_DELAY: 80
web5:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web5"
    START_DELAY: 100
web6:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web6"
    START_DELAY: 120
web7:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web7"
    START_DELAY: 140
web8:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web8"
    START_DELAY: 160
web9:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web9"
    START_DELAY: 180
web10:
  image: dkdde/forgetit_web
  links:
    - db
    - alfresco
    - gate
    - influxdb
    - mimir
  environment:
    DB_HOST: "db"
    DB_PASS: "KtE0uD5dK4rv"
    DB_PORT: "3306"
    DB_NAME: "web10"
    START_DELAY: 200
nginx:
  build: .
#  image: "dkdde/fish_nginx"
  ports:
    - "80:80"
  volumes:
    - passwd:/etc/nginx/passwd
  links:
    - web1
    - web2
    - web3
    - web4
    - web5
    - web6
    - web7
    - web8
    - web9
    - web10
    - db
    - gate
    - alfresco
db:
  image: tutum/mysql:5.5
  environment:
    MYSQL_USER: "admin"
    MYSQL_PASS: "KtE0uD5dK4rv"
    STARTUP_SQL: "/tmp/mounted/initialDatabase.sql"
  volumes:
    - database:/tmp/mounted
gate:
  image: dkdde/forgetit_gate
alfresco:
   image: dkdde/forgetit_typo3_alfresco:latest
influxdb:
  image: tutum/influxdb:0.9
  environment:
    PRE_CREATE_DB: "typo3"
mimir:
  image: dkdde/forgetit_mimir
