gate:
  image: dkdde/forgetit_gate
  container_name: 'gate'
alfresco:
  image: dkdde/forgetit_typo3_alfresco
  container_name: 'alfresco'
influxdb:
  image: tutum/influxdb:0.9
  container_name: 'influxdb'
  environment:
    PRE_CREATE_DB: 'typo3'
chronograph:
  image: lukasmartinelli/chronograf
  container_name: 'chronograph'
  environment:
    INFLUXDB_HOST: 'influxdb'
r_mimir:
  container_name: 'mimir'
  image: dkdde/forgetit_mimir
r_db:
  image: tutum/mysql:5.5
  container_name: 'db'
  environment:
    MYSQL_USER: 'admin'
    MYSQL_PASS: 'KtE0uD5dK4rv'
    STARTUP_SQL: '/tmp/mounted/review.sql'
  volumes:
    - ./database:/tmp/mounted
r_web:
  image: dkdde/forgetit_web
  container_name: 'web'
  volumes:
  - ../semantic_images:/app/typo3conf/ext/semantic_images
  environment:
    DB_HOST: 'db'
    DB_PASS: 'KtE0uD5dK4rv'
    DB_PORT: '3306'
    DB_NAME: 'review'
    FISH_EVALUATION: 'dkd'
    START_DELAY: 0
ontoaut:
  image: ksjogo/ontoaut
  container_name: 'ontoaut'
  command: 'npm run-script start-dev -- -L'
nginx:
  build: '.'
  container_name: 'nginx'
  ports:
    - '80:80'
  volumes:
    - ./passwd:/etc/nginx/passwd
